# Generated by Django 2.2.13 on 2021-02-14 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 15, 0, 16, 0, 343204)),
        ),
    ]
