# Generated by Django 2.2.13 on 2021-02-18 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_home', '0005_auto_20210217_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 14, 53, 27, 363638)),
        ),
    ]
