# Generated by Django 2.2.13 on 2021-02-18 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_home', '0006_auto_20210218_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 15, 4, 5, 434046)),
        ),
        migrations.AlterField(
            model_name='books',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdfs/%Y/%m/%d/'),
        ),
    ]
